
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGYpc6A-zzEbCU3nrtL9_W3Mb36cPLQkk',
    appId: '1:905197285217:web:55e5fd3cfbe00a84a55f20',
    messagingSenderId: '905197285217',
    projectId: 'indrek-project',
    authDomain: 'indrek-project.firebaseapp.com',
    databaseURL: 'https://indrek-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'indrek-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7NsGz3ddH9BdjfkvyyWPLToaOOv5SnEo',
    appId: '1:905197285217:android:6eefbbe7bc753bb0a55f20',
    messagingSenderId: '905197285217',
    projectId: 'indrek-project',
    databaseURL: 'https://indrek-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'indrek-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '905197285217',
    projectId: 'indrek-project',
    databaseURL: 'https://indrek-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'indrek-project.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: '905197285217',
    projectId: 'indrek-project',
    databaseURL: 'https://indrek-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'indrek-project.appspot.com',
    iosBundleId: 'com.example.myapp',
  );
}
